# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: executable
        path: StarRatingRebirth.Console/bin/publish/StarRatingRebirth.Console.exe
        retention-days: 1

    - name: Extract version
      id: extract_version
      shell: pwsh
      run: |
        $version = ./StarRatingRebirth.Console/bin/publish/StarRatingRebirth.Console.exe --version
        $version = $version.Trim()
        echo "version=$version" >> $env:GITHUB_OUTPUT
        echo "Version extracted: $version"
  
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: executable
        path: ./artifact
    
    - name: Create tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag ${{ needs.build.outputs.version }}
        git push origin ${{ needs.build.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ needs.build.outputs.version }}
        name: Release ${{ needs.build.outputs.version }}
        body: |
          Release version ${{ needs.build.outputs.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ./artifact/StarRatingRebirth.Console.exe