# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: executable
        path: StarRatingRebirth.Console/bin/publish/StarRatingRebirth.Console.exe

    - name: Extract version
      id: extract_version
      shell: pwsh
      run: |
        $content = Get-Content -Path "StarRatingRebirth/SRCalculator.cs" -Raw
        if ($content -match 'public static string Version = "([^"]+)"') {
          $version = $matches[1]
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "Version extracted: $version"
        } else {
          echo "Failed to extract version"
          exit 1
        }

    - name: Bump version and push tag
      id: tag_bump
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        CUSTOM_TAG: "${{ steps.extract_version.outputs.version }}"
        WITH_V: false

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_bump.outputs.new_tag }}
        name: Release ${{ steps.tag_bump.outputs.new_tag }}
        body: |
          Release version ${{ steps.tag_bump.outputs.new_tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: StarRatingRebirth.Console/bin/publish/StarRatingRebirth.Console.exe